In [1]:
# Librerías
import requests
import pandas as pd
from astroquery.mpc import MPC

In [3]:
# Verificar la conexión a internet.
def verificar_conexion():
    try:
        requests.get("http://www.google.com", timeout=5)
        print('✅ Conectado a internet.')
        return True
    
    except requests.ConnectionError:
        print('🛑 Sin conexión a internet.')
        return False

In [ ]:
# Conexión con la API de COBS

Link_cops_API = 'https://cobs.si/api/comet_list.api'
try: 
    if verificar_conexion():
        response = requests.get(Link_cops_API)

        if response.status_code == 200:
            content = response.json()
            print('✅ Base de datos actualizada.')

except requests.ConnectionError: 
    print(f'🛑 Se presentó un error al cargar la base de datos.\nError: {response.status_code}\n{response.content}')

🛑 Sin conexión a internet.

In [ ]:
Link_cops_API = 'https://cobs.si/api/comet.api?des=C/2023 A3'
response = requests.get(Link_cops_API)
pd.to_datetime(response.json()['object']['perihelion_date'])

Timestamp('2024-09-27 17:48:00')

In [4]:
# Conexión con la API de COBS
def Obtener_perihelio():
    try: 
        nombre_cometa = '1P'
        Link_cops_API = f'https://cobs.si/api/comet.api?des={nombre_cometa}'

        if verificar_conexion():
            response = requests.get(Link_cops_API)

            if response.status_code == 200:
                perihelio = pd.to_datetime(response.json()['object']['perihelion_date'])
                print('✅ Perihelio del cometa obtenido.')
                return perihelio
        
    except requests.ConnectionError:
        print(f'🛑 Se presentó un error al cargar la base de datos.\nError: {response.status_code}\n{response.content}')

Obtener_perihelio()

✅ Conectado a internet.
✅ Perihelio del cometa obtenido.

Timestamp('2061-09-06 17:52:00')

In [23]:
cometas_df = pd.DataFrame(content['objects'])
cometas_df

,id,type,name,fullname,mpc_name,icq_name,component,current_mag,perihelion_date,perihelion_mag,peak_mag,peak_mag_date,is_observed,is_active
0,1,N,P/2010 H2,P/2010 H2 (Vales),K10H020,P2010H2,None,14.0,2025-03-09 15:44,12.6,12.5,2025-04-09,True,True
1,2,C,C/2014 UN271,C/2014 UN271 (Bernardinelli-Bernstein),K14UR1N,2014UNR1,None,18.1,2031-01-17 03:51,16.0,15.8,2031-04-04,True,True
2,3,C,C/2020 PV6,C/2020 PV6 (PANSTARRS),K20P06V,2020PV6,None,24.9,2021-09-26 01:47,15.6,14.9,2021-08-05,True,True
3,4,A,A/2021 E4,A/2021 E4,K21E040,A2021E4,None,22.4,2022-04-24 21:51,20.1,19.8,2022-02-21,False,True
4,6,C,C/2021 G3,C/2021 G3 (PANSTARRS),K21G030,2021G3,None,24.9,2021-10-17 20:18,21.4,20.9,2022-01-31,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2228,2562,N,P/2024 R3,P/2024 R3 (PANSTARRS),K24R030,P2024R3,None,20.0,2024-05-17 00:25,21.1,19.9,2024-10-11,False,True
2229,2563,C,C/2024 R4,C/2024 R4 (PANSTARRS),K24R040,2024R4,None,20.9,2027-10-26 12:38,16.3,16.1,2028-02-29,False,True
2230,2564,P,484P,484P/Spacewatch,484P,0484,None,26.6,2028-03-10 22:56,19.9,19.7,2028-02-08,False,True
2231,2565,P,485P,485P/Sheppard-Tholen,485P,0485,None,23.2,2023-08-24 20:11,22.4,21.5,2024-01-11,False,True
2232,2566,P,486P,486P/Leonard,486P,0486,None,21.1,2025-04-03 20:26,20.5,19.5,2025-09-05,False,True

In [34]:
lista_cometas_df = cometas_df[['name', 'fullname']]
lista_cometas_df.name[lista_cometas_df.fullname.str.contains('Halley')].values[0]

'1P'

In [44]:
'1P' not in lista_cometas_df['name'].to_list()

False

In [50]:
from pathlib import Path

titulo = 'C/2023 A3'

Path('Graficas', f'{titulo}.png')

WindowsPath('Graficas/C/2023 A3.png')

In [40]:
import os 
ruta = os.path.join('Graficas', 'C/2023 A3.png')
ruta

'Graficas\\C/2023 A3.png'

In [46]:
ruta = os.path.join('Graficas', rf'{titulo}.png')
ruta, rf'{titulo}.png'

('Graficas\\C/2023 A3.png', 'C/2023 A3.png')

In [9]:
from datetime import date
print(date.today())

2024-10-01

In [4]:
try: 
    fecha_inicial = '1976-01-01'
    nombre_cometa = '1P'
    Link_cops_API_pagina_1 = f'https://cobs.si/api/obs_list.api?des={nombre_cometa}&format=json&from_date={fecha_inicial} 00:00&page=1&exclude_faint=False&exclude_not_accurate=False'

    if True:
        print(f'\n⌛ Conectando con la base de datos [COBS Observaciones].')
        response_pagina_1 = requests.get(Link_cops_API_pagina_1)

        if response_pagina_1.status_code == 200:
            content_pagina_1 = response_pagina_1.json()
            numero_de_paginas = int(content_pagina_1['info']['pages'])

            content = content_pagina_1['objects']

            for pagina in range(2, numero_de_paginas + 1):
                Link_cops_API_pagina = f'https://cobs.si/api/obs_list.api?des={nombre_cometa}&format=json&from_date={fecha_inicial}&page={pagina}&exclude_faint=False&exclude_not_accurate=False'
                response_pagina = requests.get(Link_cops_API_pagina)
                content_pagina = response_pagina.json()
                content.extend(content_pagina['objects'])

            print('✅ Base de datos actualizada [COBS Observaciones].')
        
except:
    print(f'🛑 Se presentó un error al cargar la base de datos.\nError: {response_pagina.status_code}\n{response_pagina.content}')

⌛ Conectando con la base de datos [COBS Observaciones].
✅ Base de datos actualizada [COBS Observaciones].

In [5]:
cometa_df = pd.DataFrame(content)
cometa_df['obs_method_key'] = cometa_df.obs_method.apply(
        lambda registro: registro['key'] if registro is not None and 'key' in registro else 'Dato faltante'
        )
cometa_df['obs_date'] = pd.to_datetime(pd.to_datetime(cometa_df.obs_date).dt.date)
cometa_df['magnitude'] = pd.to_numeric(cometa_df.magnitude)

curva_de_luz_cruda_df = cometa_df[['obs_method_key', 'obs_date', 'magnitude']].copy()

cometa_df.sample(3)

,type,obs_date,comet,observer,location,extinction,obs_method,comet_visibility,magnitude,conditions,...,comparison_star_magnitude,pixel_size_x,pixel_size_y,pixel_size_unit,obs_comment,obs_sky_quality,obs_sky_quality_method,reference_star_names,date_added,obs_method_key
3356,V,1986-01-14,"{'type': 'P', 'name': '1P', 'fullname': '1P/Ha...","{'first_name': 'Françoir Roger', 'last_name': ...",None,None,"{'key': 'S', 'name': 'In-Out method', 'source'...",None,4.5,None,...,None,None,None,None,,None,NaN,,2022-05-08 10:56:26,S
6074,V,1985-10-22,"{'type': 'P', 'name': '1P', 'fullname': '1P/Ha...","{'first_name': 'Daniel W. E.', 'last_name': 'G...",None,None,"{'key': 'M', 'name': 'Modified-Out method', 's...",None,8.9,None,...,None,None,None,None,,None,NaN,,2022-05-08 10:59:23,M
193,V,1986-12-06,"{'type': 'P', 'name': '1P', 'fullname': '1P/Ha...","{'first_name': 'John E.', 'last_name': 'Bortle...",None,None,"{'key': 'S', 'name': 'In-Out method', 'source'...",None,11.9,None,...,None,None,None,None,,None,NaN,,2022-05-08 10:52:53,S

In [ ]:
fecha_inicial = curva_de_luz_cruda_df.obs_date.min()
fecha_final = curva_de_luz_cruda_df.obs_date.max()
fechas = (fecha_final - fecha_inicial).days + 1 if (fecha_final - fecha_inicial).days + 1 <= 1441 else 1441
ephemeris = MPC.get_ephemeris(nombre_cometa, start = str(fecha_inicial), number = fechas)
ephemeris.to_pandas()

,Date,RA,Dec,Delta,r,Elongation,Phase,V,Proper motion,Direction
0,1981-12-02,108.025000,8.389444,12.023,12.789,139.5,2.9,19.7,10.82,268.3
1,1981-12-03,107.951667,8.387500,12.007,12.783,140.5,2.8,19.7,10.97,268.6
2,1981-12-04,107.877500,8.385833,11.992,12.778,141.5,2.7,19.7,11.12,268.9
3,1981-12-05,107.802083,8.384722,11.977,12.773,142.5,2.7,19.7,11.27,269.2
4,1981-12-06,107.725417,8.383889,11.962,12.768,143.5,2.6,19.7,11.41,269.5
...,...,...,...,...,...,...,...,...,...,...
1436,1985-11-07,71.751667,23.040278,0.853,1.787,151.5,15.4,7.4,215.65,271.9
1437,1985-11-08,70.139583,23.080556,0.829,1.773,153.9,14.2,7.3,229.61,271.2
1438,1985-11-09,68.422917,23.103889,0.805,1.758,156.5,13.0,7.2,244.27,270.5
1439,1985-11-10,66.597083,23.106667,0.783,1.744,159.1,11.7,7.1,259.59,269.7
1440,1985-11-11,64.658333,23.085556,0.761,1.730,161.9,10.3,7.0,275.51,268.9

In [25]:
import requests

response = requests.get("https://data.minorplanetcenter.net/api/get-orb", json={"desig": "2212"})

if response.ok:
    mpc_orb = response.json()[0]['mpc_orb']
    print(mpc_orb)
else:
    print("Error: ", response.status_code, response.content)

[{'CAR': {'coefficient_names': ['x', 'y', 'z', 'vx', 'vy', 'vz'], 'coefficient_uncertainties': [4.23903e-08, 2.13245e-08, 5.08136e-08, 6.20497e-11, 7.39209e-11, 9.82639e-11], 'coefficient_values': [1.333178361802, 3.31612890099785, 0.469115040090068, -0.00489356132738167, -0.00192205800927489, 9.56476061593146e-05], 'covariance': {'cov00': 1.796936422166611e-15, 'cov01': -6.518609416266976e-16, 'cov02': -3.701034729637134e-16, 'cov03': -8.314036498003137e-19, 'cov04': 2.163597017176545e-18, 'cov05': -4.335778875007487e-19, 'cov06': None, 'cov07': None, 'cov08': None, 'cov09': None, 'cov11': 4.547363117854558e-16, 'cov12': -3.552001592238185e-16, 'cov13': 9.78770064094364e-19, 'cov14': -1.014273245741714e-18, 'cov15': 9.484870302753811e-20, 'cov16': None, 'cov17': None, 'cov18': None, 'cov19': None, 'cov22': 2.582017519532128e-15, 'cov23': -3.36184792030451e-19, 'cov24': -4.581236736293791e-19, 'cov25': -1.69900980242869e-18, 'cov26': None, 'cov27': None, 'cov28': None, 'cov29': None, 'cov33': 3.850164485704323e-21, 'cov34': -3.313062350619725e-21, 'cov35': -8.1051488626765e-22, 'cov36': None, 'cov37': None, 'cov38': None, 'cov39': None, 'cov44': 5.464292985734213e-21, 'cov45': -9.617735593427023e-22, 'cov46': None, 'cov47': None, 'cov48': None, 'cov49': None, 'cov55': 9.655784991864163e-21, 'cov56': None, 'cov57': None, 'cov58': None, 'cov59': None, 'cov66': None, 'cov67': None, 'cov68': None, 'cov69': None, 'cov77': None, 'cov78': None, 'cov79': None, 'cov88': None, 'cov89': None, 'cov99': None}, 'eigenvalues': [4.11631e-12, 5.1143e-11, 8.55543e-11, 1.00535e-08, 4.47117e-08, 5.22828e-08]}, 'COM': {'coefficient_names': ['q', 'e', 'i', 'node', 'argperi', 'peri_time'], 'coefficient_uncertainties': [1.24923e-08, 5.74889e-09, 1.25311e-06, 5.23644e-06, 5.13062e-06, 1.52522e-06], 'coefficient_values': [0.357435154004957, 0.835085158241367, 11.2267956517173, 26.7023462839278, 210.3491990530559, 60001.9533880349], 'covariance': {'cov00': 1.560568997510154e-16, 'cov01': -7.180724326184275e-17, 'cov02': 3.850985838244219e-15, 'cov03': 9.330895659501323e-15, 'cov04': -1.051953689284678e-14, 'cov05': 1.229817515660765e-14, 'cov06': None, 'cov07': None, 'cov08': None, 'cov09': None, 'cov11': 3.30497694241748e-17, 'cov12': -1.809549749096511e-15, 'cov13': -4.313877974803639e-15, 'cov14': 4.854976058848152e-15, 'cov15': -5.636508689353544e-15, 'cov16': None, 'cov17': None, 'cov18': None, 'cov19': None, 'cov22': 1.57029220733409e-12, 'cov23': 3.215425682973358e-12, 'cov24': -3.029896560961398e-12, 'cov25': -8.722885160871852e-15, 'cov26': None, 'cov27': None, 'cov28': None, 'cov29': None, 'cov33': 2.742028218439032e-11, 'cov34': -2.656526878299943e-11, 'cov35': 1.567507433939742e-13, 'cov36': None, 'cov37': None, 'cov38': None, 'cov39': None, 'cov44': 2.632321302902965e-11, 'cov45': 2.241137956205752e-13, 'cov46': None, 'cov47': None, 'cov48': None, 'cov49': None, 'cov55': 2.326292744630269e-12, 'cov56': None, 'cov57': None, 'cov58': None, 'cov59': None, 'cov66': None, 'cov67': None, 'cov68': None, 'cov69': None, 'cov77': None, 'cov78': None, 'cov79': None, 'cov88': None, 'cov89': None, 'cov99': None}, 'eigenvalues': [7.77145e-11, 6.12306e-09, 1.1801e-08, 1.9379e-08, 1.28054e-07, 1.52525e-06]}, 'categorization': {'object_type_int': 0, 'object_type_str': 'Minor Planet', 'orbit_subtype_int': None, 'orbit_subtype_str': '', 'orbit_type_int': 2, 'orbit_type_str': 'Apollo'}, 'designation_data': {'designation_count': 1, 'iau_name': '', 'name': 'Hephaistos', 'orbfit_name': '2212', 'packed_primary_provisional_designation': 'J78S00B', 'packed_secondary_provisional_designations': [], 'permid': '2212', 'unpacked_primary_provisional_designation': '1978 SB', 'unpacked_secondary_provisional_designations': []}, 'epoch_data': {'epoch': 60800.0, 'timeform': 'MJD', 'timesystem': 'TDT'}, 'magnitude_data': {'G': 0.15, 'G1': None, 'G12': None, 'G2': None, 'H': 13.498, 'photometric_model': '????'}, 'moid_data': {'Earth': 0.11226, 'Jupiter': None, 'Mars': None, 'Venus': None}, 'non_grav_booleans': {'non_grav_coefficients': {'A1': False, 'A2': False, 'A3': False, 'DT': False, 'srp': False, 'yarkovski': False}, 'non_grav_model': {'marsden': False, 'srp': False, 'yabushita': False, 'yarkovski': False, 'yc': False}, 'non_gravs': False}, 'orbit_fit_statistics': {'U_param': 0.0, 'arc_length_sel': 0, 'arc_length_total': 0, 'nobs_optical': 0, 'nobs_optical_sel': 0, 'nobs_radar': 0, 'nobs_radar_sel': 0, 'nobs_total': 0, 'nobs_total_sel': 0, 'nopp': 0, 'normalized_RMS': 0.0, 'not_normalized_RMS': 0.0, 'numparams': 6, 'orbit_quality': 'no_orbit', 'score1': 0.0, 'score2': 0.0, 'sig_to_noise_ratio': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'snr_below_1': False, 'snr_below_3': False}, 'software_data': {'fitting_datetime': '2025-02-26 14:00:58', 'fitting_software_name': 'orbfit', 'fitting_software_version': '1.0', 'mpcorb_creation_datetime': '2025-02-26 14:01:17', 'mpcorb_version': '0.4'}, 'system_data': {'EclipticObliquityArcseconds': '84381.448', 'eph': 'DE431', 'force_model': '????', 'refframe': 'ICRF', 'refsys': 'Ecliptic'}}]

In [29]:
mpc_orb[0]

{'CAR': {'coefficient_names': ['x', 'y', 'z', 'vx', 'vy', 'vz'],
  'coefficient_uncertainties': [4.23903e-08,
   2.13245e-08,
   5.08136e-08,
   6.20497e-11,
   7.39209e-11,
   9.82639e-11],
  'coefficient_values': [1.333178361802,
   3.31612890099785,
   0.469115040090068,
   -0.00489356132738167,
   -0.00192205800927489,
   9.56476061593146e-05],
  'covariance': {'cov00': 1.796936422166611e-15,
   'cov01': -6.518609416266976e-16,
   'cov02': -3.701034729637134e-16,
   'cov03': -8.314036498003137e-19,
   'cov04': 2.163597017176545e-18,
   'cov05': -4.335778875007487e-19,
   'cov06': None,
   'cov07': None,
   'cov08': None,
   'cov09': None,
   'cov11': 4.547363117854558e-16,
   'cov12': -3.552001592238185e-16,
   'cov13': 9.78770064094364e-19,
   'cov14': -1.014273245741714e-18,
   'cov15': 9.484870302753811e-20,
   'cov16': None,
   'cov17': None,
   'cov18': None,
   'cov19': None,
   'cov22': 2.582017519532128e-15,
   'cov23': -3.36184792030451e-19,
   'cov24': -4.581236736293791e-19,
   'cov25': -1.69900980242869e-18,
   'cov26': None,
   'cov27': None,
   'cov28': None,
   'cov29': None,
   'cov33': 3.850164485704323e-21,
   'cov34': -3.313062350619725e-21,
   'cov35': -8.1051488626765e-22,
   'cov36': None,
   'cov37': None,
   'cov38': None,
   'cov39': None,
   'cov44': 5.464292985734213e-21,
   'cov45': -9.617735593427023e-22,
   'cov46': None,
   'cov47': None,
   'cov48': None,
   'cov49': None,
   'cov55': 9.655784991864163e-21,
   'cov56': None,
   'cov57': None,
   'cov58': None,
   'cov59': None,
   'cov66': None,
   'cov67': None,
   'cov68': None,
   'cov69': None,
   'cov77': None,
   'cov78': None,
   'cov79': None,
   'cov88': None,
   'cov89': None,
   'cov99': None},
  'eigenvalues': [4.11631e-12,
   5.1143e-11,
   8.55543e-11,
   1.00535e-08,
   4.47117e-08,
   5.22828e-08]},
 'COM': {'coefficient_names': ['q', 'e', 'i', 'node', 'argperi', 'peri_time'],
  'coefficient_uncertainties': [1.24923e-08,
   5.74889e-09,
   1.25311e-06,
   5.23644e-06,
   5.13062e-06,
   1.52522e-06],
  'coefficient_values': [0.357435154004957,
   0.835085158241367,
   11.2267956517173,
   26.7023462839278,
   210.3491990530559,
   60001.9533880349],
  'covariance': {'cov00': 1.560568997510154e-16,
   'cov01': -7.180724326184275e-17,
   'cov02': 3.850985838244219e-15,
   'cov03': 9.330895659501323e-15,
   'cov04': -1.051953689284678e-14,
   'cov05': 1.229817515660765e-14,
   'cov06': None,
   'cov07': None,
   'cov08': None,
   'cov09': None,
   'cov11': 3.30497694241748e-17,
   'cov12': -1.809549749096511e-15,
   'cov13': -4.313877974803639e-15,
   'cov14': 4.854976058848152e-15,
   'cov15': -5.636508689353544e-15,
   'cov16': None,
   'cov17': None,
   'cov18': None,
   'cov19': None,
   'cov22': 1.57029220733409e-12,
   'cov23': 3.215425682973358e-12,
   'cov24': -3.029896560961398e-12,
   'cov25': -8.722885160871852e-15,
   'cov26': None,
   'cov27': None,
   'cov28': None,
   'cov29': None,
   'cov33': 2.742028218439032e-11,
   'cov34': -2.656526878299943e-11,
   'cov35': 1.567507433939742e-13,
   'cov36': None,
   'cov37': None,
   'cov38': None,
   'cov39': None,
   'cov44': 2.632321302902965e-11,
   'cov45': 2.241137956205752e-13,
   'cov46': None,
   'cov47': None,
   'cov48': None,
   'cov49': None,
   'cov55': 2.326292744630269e-12,
   'cov56': None,
   'cov57': None,
   'cov58': None,
   'cov59': None,
   'cov66': None,
   'cov67': None,
   'cov68': None,
   'cov69': None,
   'cov77': None,
   'cov78': None,
   'cov79': None,
   'cov88': None,
   'cov89': None,
   'cov99': None},
  'eigenvalues': [7.77145e-11,
   6.12306e-09,
   1.1801e-08,
   1.9379e-08,
   1.28054e-07,
   1.52525e-06]},
 'categorization': {'object_type_int': 0,
  'object_type_str': 'Minor Planet',
  'orbit_subtype_int': None,
  'orbit_subtype_str': '',
  'orbit_type_int': 2,
  'orbit_type_str': 'Apollo'},
 'designation_data': {'designation_count': 1,
  'iau_name': '',
  'name': 'Hephaistos',
  'orbfit_name': '2212',
  'packed_primary_provisional_designation': 'J78S00B',
  'packed_secondary_provisional_designations': [],
  'permid': '2212',
  'unpacked_primary_provisional_designation': '1978 SB',
  'unpacked_secondary_provisional_designations': []},
 'epoch_data': {'epoch': 60800.0, 'timeform': 'MJD', 'timesystem': 'TDT'},
 'magnitude_data': {'G': 0.15,
  'G1': None,
  'G12': None,
  'G2': None,
  'H': 13.498,
  'photometric_model': '????'},
 'moid_data': {'Earth': 0.11226, 'Jupiter': None, 'Mars': None, 'Venus': None},
 'non_grav_booleans': {'non_grav_coefficients': {'A1': False,
   'A2': False,
   'A3': False,
   'DT': False,
   'srp': False,
   'yarkovski': False},
  'non_grav_model': {'marsden': False,
   'srp': False,
   'yabushita': False,
   'yarkovski': False,
   'yc': False},
  'non_gravs': False},
 'orbit_fit_statistics': {'U_param': 0.0,
  'arc_length_sel': 0,
  'arc_length_total': 0,
  'nobs_optical': 0,
  'nobs_optical_sel': 0,
  'nobs_radar': 0,
  'nobs_radar_sel': 0,
  'nobs_total': 0,
  'nobs_total_sel': 0,
  'nopp': 0,
  'normalized_RMS': 0.0,
  'not_normalized_RMS': 0.0,
  'numparams': 6,
  'orbit_quality': 'no_orbit',
  'score1': 0.0,
  'score2': 0.0,
  'sig_to_noise_ratio': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  'snr_below_1': False,
  'snr_below_3': False},
 'software_data': {'fitting_datetime': '2025-02-26 14:00:58',
  'fitting_software_name': 'orbfit',
  'fitting_software_version': '1.0',
  'mpcorb_creation_datetime': '2025-02-26 14:01:17',
  'mpcorb_version': '0.4'},
 'system_data': {'EclipticObliquityArcseconds': '84381.448',
  'eph': 'DE431',
  'force_model': '????',
  'refframe': 'ICRF',
  'refsys': 'Ecliptic'}}

In [30]:
from datetime import datetime, timedelta

# Número que representa días desde una fecha base
numero_dias = mpc_orb[0]['COM']['coefficient_values'][-1]

# Definir la fecha base (1 de enero de 1970)
fecha_base = datetime(1970, 1, 1)

# Calcular la fecha sumando los días
fecha_resultante = fecha_base + timedelta(days=numero_dias)

# Mostrar la fecha resultante
print(fecha_resultante)

2134-04-12 22:52:52.726215

In [21]:
1970-110

1860